examples/requirements.txt
examples/s3_instrument.py
examples/torchvision_demo.py

added instrumentation-related things

OS-6654 extended examples

---

optscale_arcee/instrumentation/__init__.py
optscale_arcee/instrumentation/patch.py
optscale_arcee/instrumentation/redshift_connector/__init__.py
optscale_arcee/instrumentation/redshift_connector/stats.py
optscale_arcee/instrumentation/redshift_connector/wrapper.py
optscale_arcee/instrumentation/utils.py

Track queries executed by redshift_connector as instrumentation stats

OS-6713 redshift_connector instrumentation

---

optscale_arcee/collectors/console.py
optscale_arcee/collectors/git.py

- fixed arcee for py38 and below
- collect git info on executable dir

OS-7025 collectors fixes

---

setup.cfg

OS-7171. Updated version to 0.1.37

---

README.md
examples/simple.py
optscale_arcee/__init__.py
optscale_arcee/arcee.py
optscale_arcee/sender/sender.py

OS-7325. Added model/set_version funcs

---

optscale_arcee/sender/sender.py

OS-7392. str wrapping for version

---

README.md

OS-7553. Fixed typo in README.md

---

optscale_arcee/arcee.py
optscale_arcee/sender/sender.py

OS-7487. Changed model version urls

---

examples/linear_regression.py
examples/torchvision_demo.py
optscale_arcee/arcee.py

OS-7490. Removed deprecation warning and extended samples

---

setup.cfg

optscale-arcee version 0.1.40

---

README.md
examples/simple.py
examples/torchvision_demo.py
optscale_arcee/__init__.py
optscale_arcee/arcee.py
optscale_arcee/sender/sender.py
setup.cfg

OS-7560. Support run artifacts apis

---

README.md
examples/simple.py
examples/torchvision_demo.py
optscale_arcee/__init__.py
optscale_arcee/arcee.py
optscale_arcee/sender/sender.py
setup.cfg

Merge feature/ml_artifacts into main

Merge feature/ml_artifacts into main

---

README.md
optscale_arcee/arcee.py
optscale_arcee/sender/sender.py

OS-7677. Registering dataset improvements and default artifact description

---

setup.cfg

OS-7677. Version 0.1.42

---

README.md
setup.cfg

OS-6478. Updated README.md

---

optscale_arcee/platform.py
setup.cfg
tests/test_platform.py

OS-5394. Support Alibaba cloud platform

---

optscale_arcee/platform.py
setup.cfg
tests/test_platform.py

OS-5393. Support GCP platform

---

examples/linear_regression.py

OS-7941. Improved linear_regression example

---

README.md
setup.cfg

OS-8000. Updated README.md

---

.github/workflows/lint-test.yaml
README.md
examples/torchvision_demo.py
optscale_arcee/collectors/hardware.py
optscale_arcee/libs/GPUtil/GPUtil.py
optscale_arcee/libs/GPUtil/__init__.py
optscale_arcee/libs/GPUtil/demo_GPUtil.py
optscale_arcee/libs/__init__.py
optscale_arcee/platform.py
setup.cfg
tox.ini

- updated aiohttp 3.10.11 to support Py3.12
- IMDSv2 support 
- integrated  GPUtil + Py3.12 support
** Note - feel free to skip reviewing GPUtil source, because only Pep8 and Py3.12 fixed has been applied.

OSN-597: AWS IMDSv2 support
